apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-assignment-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-assignment
      track: green
  template:
    metadata:
      labels:
        app: scalable-assignment
        track: green
    spec:
      containers:
        - name: flask-api
          image: varkey93704/scalable-assignment:v1.2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
